#!/usr/bin/env bash
set -e

DOCKER_NAME=${DOCKER_CONTAINER_NAME:-app}

function err() {
	echo "$1" 
	exit -1
}

function main() {
	case $1 in
		doctor)
			set -v
			(docker -v 2>/dev/null && echo "Looks like you're ready to go") || err "Please Install Docker"
			;;
		init)
			set -v
			docker build -t $DOCKER_NAME .
			;;
		setup)
			set -v
			docker run -v $(pwd):/app $DOCKER_NAME vendor/gyp/gyp --depth=. -f ninja build.gyp
			;;
		build)
			set -v
			docker run -v $(pwd):/app $DOCKER_NAME ninja -C out/Default
			;;
		clean)
			set -v
			rm -rf out
			;;
		*)
			err "Unknown Command: $1"
			;;

	esac
}

if [ "$#" -le 0 ]; then
	echo "Usage: $0 COMMAND"
	cat <<-EOF
		COMMANDS

		setup  setup ninja build directory
		build  build with ninja
	EOF
elif [ "$#" -gt 1 ]; then
	# support multiple commands via recursive invocation
	$0 $1 && $0 ${*:2}
else [ "$#" -eq 1 ]; 
	echo "Running: $1"
	main $1
fi

